name: Discord Webhook
on: [push]
jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
    - name: fancier-discord-webhooks
      uses: baked-libs/maven-discord-integration@1.5.1
      with:
        id: "1082255775218544680"
        token: "40Gj0cyY7nsCxoiy9Rk1GCpB6FhaHb-4OvF2Z5xqGGhiRG0-1Hjk-dTObJ1eauSiLZ6p"
